- .github/workflows/publish.yml
- .github/workflows/release.yml
- zenoh-kotlin/build.gradle.kts
Workflow to automatically publish a package into a github packages, containing the built android library.
Manually tested on private repository.
> Adding publishing github workflow

- .github/workflows/documentation.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
* Fix Release workflow failing by:
* Extraction the documentation building job into a separate workflow file
* Fixing error in that workflow
* Publishing workflow modification
* Removing cron schedule. Now the publication of packages must be done manually.
> Fix workflows & refactor

- .github/workflows/ci.yml
- zenoh-jni/Cargo.toml
See https://github.com/eclipse-zenoh/zenoh/pull/639.
> Reduce status checks

- zenoh-jni/Cargo.lock
- zenoh-jni/Cargo.toml
- zenoh-jni/src/logger.rs
- zenoh-jni/src/publisher.rs
- zenoh-jni/src/put.rs
- zenoh-jni/src/query.rs
- zenoh-jni/src/queryable.rs
- zenoh-jni/src/reply.rs
- zenoh-jni/src/session.rs
- zenoh-jni/src/subscriber.rs
- zenoh-jni/src/utils.rs
- zenoh-jni/src/value.rs
Sister of: https://github.com/eclipse-zenoh/zenoh/pull/895
> feat(tracing): using tracing instead of log

- examples/src/main/kotlin/io.zenoh/ZDelete.kt
- examples/src/main/kotlin/io.zenoh/ZGet.kt
- examples/src/main/kotlin/io.zenoh/ZPub.kt
- examples/src/main/kotlin/io.zenoh/ZPubThr.kt
- examples/src/main/kotlin/io.zenoh/ZPut.kt
- examples/src/main/kotlin/io.zenoh/ZQueryable.kt
- examples/src/main/kotlin/io.zenoh/ZSub.kt
- examples/src/main/kotlin/io.zenoh/ZSubThr.kt
* Fixing examples after changes from PR #107 .
* For each example, displaying the example first and then the arguments parsing logic.
> Fix examples + moving down the args parsing logic of all the examples

- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/ConsolidationMode.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Get.kt
> Change default consolidation mode to AUTO

- zenoh-jni/src/key_expr.rs
When processing the internal string representation of a kotlin KeyExpr instance through JNI, a rust KeyExpr instance was generated through the "try_from" function. This is unnecessary since the string representation was already validated during the construction phase of the KeyExpr object on Kotlin. Therefore, this commit introduces an optimization in which the rust key expression is created with "from_string_unchecked", since we already guarantee that the string representation provided is valid and has already been checked.
> Optimizing KeyExpr processing

- examples/src/main/kotlin/io.zenoh/Config.kt
- zenoh-jni/Cargo.lock
- zenoh-jni/Cargo.toml
- zenoh-jni/src/session.rs
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
- zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
- zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
> refactor(config): enabling config for JSON, JSON5 and YAML.

- examples/src/main/kotlin/io.zenoh/Config.kt
Fix error introduced by PR #188
> fix(examples): load config error

- zenoh-jni/src/scouting.rs
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/scouting/Scout.kt
- zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
Fix error reported under issue #202. 
Also, the API is reworked in order to return a Result when launching a scout.
Close #202
> fix(scout): error when closing scout + API rework

- examples/src/main/kotlin/io.zenoh/ZSubThr.kt
- zenoh-jni/src/session.rs
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Delete.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Put.kt
Related to issue https://github.com/eclipse-zenoh/zenoh/issues/1348
> Moving reliability config param from subscriber to the publisher, and to session put and delete

- zenoh-jni/Cargo.toml
- zenoh-jni/src/session.rs
- zenoh-jni/src/zenoh_id.rs
See https://github.com/eclipse-zenoh/zenoh/pull/1419.
> Point Cargo manifest to `internal-config` branch

- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt
- zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
> fix(scouting): error when providing config

- zenoh-jni/Cargo.lock
- zenoh-jni/src/query.rs
- zenoh-jni/src/scouting.rs
- zenoh-jni/src/session.rs
> Align with Rust

- zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Reverts eclipse-zenoh/zenoh-kotlin#250
Solves issue #253
> Revert "Native lib loading refactor"

- zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionInfoTest.kt
Fixing a `SessionInfo` test that was failing locally on an Ubuntu environment.
> Fix SessionInfoTest failing on Ubuntu

- .github/workflows/ci.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/release.yml
- zenoh-kotlin/build.gradle.kts
- add `secrets: inherit` for CI workflows
- add optional debug input to debug gradle
- pass gpg key id to gradle
> fix: inherit secret and add debug for workflows

- build.gradle.kts
Inspired by https://github.com/gradle-nexus/publish-plugin/issues/120#issuecomment-929362061
> Maven publication: modifying nexus url

- rust-toolchain.toml
- zenoh-jni/src/key_expr.rs
- zenoh-jni/src/session.rs
Depends on https://github.com/eclipse-zenoh/zenoh/pull/1803
> Bump Rust toolchain to 1.85

- examples/src/main/kotlin/io.zenoh/ZQuerier.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Querier.kt
Stabilize querier API
sister PR to https://github.com/eclipse-zenoh/zenoh/pull/2051
> Stabilize querier API
