examples/src/main/kotlin/io.zenoh/ZDelete.kt, examples/src/main/kotlin/io.zenoh/ZGet.kt, examples/src/main/kotlin/io.zenoh/ZPub.kt, examples/src/main/kotlin/io.zenoh/ZQueryable.kt, examples/src/main/kotlin/io.zenoh/ZSub.kt, examples/src/main/kotlin/io.zenoh/ZSubThr.kt, zenoh-kotlin/src/main/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/main/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/main/kotlin/io/zenoh/subscriber/Subscriber.kt
Refactoring the examples for zenoh kotlin.
- Emphasizing use of try with resources (aka 'use' in kotlin)
- Removing config parameters for ZSub example (caused confusion)
- Tidying up examples
=> Examples refactor.

.github/workflows/ci.yml, zenoh-jni/Cargo.lock, zenoh-jni/Cargo.toml, zenoh-jni/src/lib.rs
To be merged after: https://github.com/eclipse-zenoh/zenoh/pull/604
Before merging, the PR should point to master.
Sister PR: https://github.com/eclipse-zenoh/zenoh-c/pull/204
https://github.com/eclipse-zenoh/zenoh-python/pull/114
=> Feature cleanup

zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
In openjdk, the os.arch is reported as amd64 for x86_64 system.
=> fix(jvm target): adding amd64 check for targets

zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
A strange issue was thrown when loading the zenoh-jni native library from the package:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\....\AppData\Local\Temp\tempLib10649058771145031396: Can't find dependent libraries
at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
at java.base/java.lang.Runtime.load0(Runtime.java:755)
at java.base/java.lang.System.load(System.java:1953)
at …
```
=> fix(windows loading): expliciting temp file suffix

zenoh-jni/src/query.rs, zenoh-jni/src/reply.rs, zenoh-jni/src/subscriber.rs
User attachment JNI byte array is not freed, causing a memory leak.
=> fix(mem leak): user attachment bytes not being freed

examples/README.md, examples/build.gradle.kts, examples/src/main/kotlin/io.zenoh/Config.kt, examples/src/main/kotlin/io.zenoh/ZDelete.kt, examples/src/main/kotlin/io.zenoh/ZGet.kt, examples/src/main/kotlin/io.zenoh/ZPub.kt, examples/src/main/kotlin/io.zenoh/ZPubThr.kt, examples/src/main/kotlin/io.zenoh/ZPut.kt, examples/src/main/kotlin/io.zenoh/ZQueryable.kt, examples/src/main/kotlin/io.zenoh/ZSub.kt, examples/src/main/kotlin/io.zenoh/ZSubThr.kt, examples/src/main/kotlin/io/zenoh/config/Config.kt, zenoh-jni/Cargo.lock, zenoh-jni/src/publisher.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/sample/Attachment.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/PublisherTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/UserAttachmentTest.kt
Using Clickt to allow users to specify arguments when running examples on Kotlin.
For instance the ZPub example, you run it using gradle, and providing the arguments the following way:
```bash
gradle ZPub --args="<your arguments>"
```
** Example: **
```bash
gradle ZPub --args="-h"
```
will display the help menu with the available arguments:
```
> Task :examples:ZPub
Usage: zpub [<options>]
Zenoh Pub example
Options:
-e, --connect=<connect>  Endpoints to connect to.
-c, --config=<config>    A configuration file.
-k, --key=<key>          The key expression to write to [default:
demo/example/zenoh-kotlin-pub]
-l, --listen=<listen>    Endpoints to listen on.
-m, --mode=<mode>        The session mode. Default: peer. Possible values:
[peer, client, router]
-v, --value=<value>      The value to …
```
=> Adding command line arguments for Kotlin examples

examples/src/main/kotlin/io.zenoh/ZPub.kt, examples/src/main/kotlin/io.zenoh/ZPubThr.kt, examples/src/main/kotlin/io.zenoh/ZQueryable.kt, examples/src/main/kotlin/io.zenoh/ZSub.kt, examples/src/main/kotlin/io.zenoh/ZSubThr.kt
These changes remove reading from stdin for all examples, and align their behaviors and outputs across projects.
This PR is part of an effort across currently active Zenoh projects. To maintain examples' implementations as close to each other as possible, any changes identified in other projects will be replicated in this PR. As such, **please do not merge these changes until all PRs are ready for merging**.
Related PRs:
- https://github.com/eclipse-zenoh/zenoh/pull/768
- https://github.com/eclipse-zenoh/zenoh-c/pull/255
- https://github.com/eclipse-zenoh/zenoh-cpp/pull/103
- https://github.com/eclipse-zenoh/zenoh-java/pull/45
- https://github.com/eclipse-zenoh/zenoh-pico/pull/359
- https://github.com/eclipse-zenoh/zenoh-python/pull/150
=> Align examples and remove reading from stdin

.github/workflows/ci.yml
The CI workflow was failing because macos-latest now refers to macos-14 and the nttld/setup-ndk action doesn't support AArch64.
=> fix: Use macos-13 instead of macos-14 runners in CI workflow

.github/workflows/release.yml
[Publishing workflows (JVM, Android, Dokka) aren't passed the release branch input.](https://github.com/eclipse-zenoh/zenoh-kotlin/actions/runs/8895450205)
=> fix: Unset `branch` input in publishing workflows

.github/workflows/publish-jvm.yml, rust-toolchain.toml
First change is to update how cross is installed via cargo. Add +stable option to cargo and install via crates.io instead of git. This way we have better control over the version of cross that will get installed.
Second change is to bump the rustc version to 1.72.0 to match the zenoh version.
=> Update rustc version and how cross is installed via cargo

examples/src/main/kotlin/io.zenoh/ZGet.kt, examples/src/main/kotlin/io.zenoh/ZQueryable.kt, examples/src/main/kotlin/io.zenoh/ZSub.kt, examples/src/main/kotlin/io.zenoh/ZSubThr.kt
For someone who's not familiar with Kotlin channels (like me before using them with this library) the current syntax of the examples might look too verbose. 
I think using the `for` loop makes it a bit easier to parse, and seems to be more idiomatic according to [Kotlin's docs](https://kotlinlang.org/docs/channels.html)
Other changes:
- Used `when` case for Get replies
- Changed the lambda paramters in `examples/src/main/kotlin/io.zenoh/ZSubThr.kt` to make it similar to other examples
=> Use for loop for kotlin Channels in examples

.github/workflows/publish-jvm.yml
Fix https://github.com/eclipse-zenoh/zenoh-kotlin/issues/99
=> fix: cargo-deb install from +stable and --locked

zenoh-jni/src/key_expr.rs, zenoh-jni/src/publisher.rs, zenoh-jni/src/put.rs, zenoh-jni/src/query.rs, zenoh-jni/src/queryable.rs, zenoh-jni/src/reply.rs, zenoh-jni/src/session.rs, zenoh-jni/src/subscriber.rs, zenoh-jni/src/utils.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIKeyExpr.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuery.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNIGetCallback.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNIQueryableCallback.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNISubscriberCallback.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/KeyExpr.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SubscriberTest.kt
This PR addresses a series of issues caused by a design flaw of the `KeyExpr` class.
---
The previous design of the KeyExpr class made that everyone of its instances had to be associated to a native key expression through the means of a pointer in order for it to be a valid instance. This caused an overly reliance on the `finalize()` function in order to free the native pointer, which is highly impactful in cases of high frequency communication due to the fact that the finalize `function` messes with all the garbage collector's optimisations, causing the instances of key expressions to not be freed as fast as they are allocated due to incoming samples. 
This PR introduces changes on the architecture of the `KeyExpr` class that aim to fix that issue. It now relies mostly on a string …
=> Modifying key expression handling

.github/workflows/publish-jvm.yml
artifacts actions v3 are deprecated
=> chore: Update artifacts action to v4

zenoh-jni/Cargo.lock, zenoh-jni/src/publisher.rs, zenoh-jni/src/session.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
* Removing functions that allowed users to dynamically set the QoS parameters after [Zenoh PR #1124](https://github.com/eclipse-zenoh/zenoh/pull/1124), those being `Publisher.setCongestionControl(cc)` and `Publisher.setPriority(priority)`.
* Allowing users to specify the `express` QoS config parameter while building the publisher.
* Some refactoring on the zenoh-jni code regarding the publisher.
=> Removing setPriority and setCongestionControl from publisher + adding express config to publisher builder

.github/workflows/ci.yml
See https://github.com/eclipse-zenoh/zenoh-kotlin/actions/runs/9834331303
=> fix: wrong syntax in ci workflow

.github/workflows/ci.yml, .github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, README.md, zenoh-kotlin/build.gradle.kts
Users not interested in targeting Android were still required to have installed the Android SDK and the NDK.
This PR refactors the `build.gradle.kts` script in order to dynamically load the Android configuration, based on the `android` property.
Example:
- To publish the Android package on maven local, do:
```
gradle -Pandroid=true publishAndroidReleaseToMavenLocal
```
- To build the JVM package, do:
```
gradle publishJvmReleaseToMavenLocal
```
(the `android` property is false by default).
The CI is updated to match these changes. The JVM publication workflow doesn't need anymore the SDK nor the NDK.
The Android publication workflow now has enabled the `-Pandroid=true` property on the publication command.
This PR was tested locally and through the CI here: …
=> Using 'android' property to enable/disable Android configuration

.github/workflows/publish-android.yml, .github/workflows/publish-dokka.yml, .github/workflows/publish-jvm.yml, zenoh-kotlin/build.gradle.kts
- Update `buildDir()` usage according to https://docs.gradle.org/current/userguide/upgrading_version_8.html#project_builddir
- Update gradle wrapper to use new action https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation
- Update gradle actions to not use arguments: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated
=> fix: Update gradle actions to newer versions

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
To reproduce:
```
@Test
fun sessionOpeningFailure() = repeat(100) {
val invalidConfig = Config.from(Path.of("invalid"))
assertFailsWith<SessionException> { Session.open(invalidConfig).getOrThrow() }
System.gc()
}
```
=> Fix JVM crash when finalizing a session that wasn't properly initialized

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/SessionDeclaration.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/KeyExpr.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/queryable/Queryable.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/subscriber/Subscriber.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
Zenoh declarations ran for as long as the Kotlin variable representing them was kept alive. This meant that whenever the user lost track of the variable, it got garbage collected and undeclared in the process. This behavior seems to be counterintuitive for programmers used to garbage collected languages (see https://github.com/eclipse-zenoh/zenoh-kotlin/issues/43).
Therefore in this PR we provide the following change: we keep track of session declarations in a list inside the session, allowing users to keep running them despite losing their references. When the session is finalized, the associated declarations are undeclared. In case the user needs to close a declaration earlier, they need to keep the variable in order to undeclare it.
=> Allowing session declarations to stay alive for the lifespan of a session.

examples/src/main/kotlin/io.zenoh/ZGet.kt, zenoh-jni/src/utils.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/ConsolidationMode.kt
Mainly motivated by the need to align default behavior of `get` with implementations in other bindings.
Sister PR:
=> Add Query `Consolidation::Auto` to JNI and Kotlin API

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt
This PR aligns zenoh-kotlin default ConsolidationMode of `Session.get` with the other bindings.
=> Use default ConsolidationMode in Session.get

examples/src/main/kotlin/io.zenoh/Config.kt, zenoh-jni/src/config.rs, zenoh-jni/src/lib.rs, zenoh-jni/src/scouting.rs, zenoh-jni/src/session.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIZBytes.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionTest.kt
Changes:
- Removing `Config.Format` enum
- Immediately returning a Result when creating a config (previously the error would arise only when attempting to open a session).
- Replacing `Config.from(string, format)` with `Config.fromJson(string)`, `Config.fromJson5(string)`, `Config.fromYaml(string)`, where each of these functions returns a `Result<Config>`.
- Replacing `Config.from(file)` with `Config.fromFile(File file): Result<Config>` and `Config.fromFile(Path path): Result<Config>`. 
- `Config.default()` still returns a Config (without result, as it's guaranteed it is successfully created by the library).
Internally, when creating a config, the value provided is processed natively, associating each Config instance to a native config instance. The native instance of the config is freed …
=> Api alignment: Config alignment

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/IntoSelector.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/Parameters.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/selector/Selector.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/GetTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ParametersTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SelectorTest.kt
Providing alignment to the selector API with the following changes:
- Creating the `Parameters` class with the following interface:
- `fun isEmpty(): Boolean`
- `fun containsKey(key: String): Boolean`
- `fun get(key: String): String?`
- `fun getOrDefault(key: String, default: String): String`
- `fun values(key: String): List<String>?`
- `fun insert(key: String, value: String): String?`
- `fun remove(key: String): String?`
- `fun extend(params: IntoParameters)`
- `fun extend(params: Map<String, String>)`
- `fun toMap(): Map<String, String>`
Closes #67
=> api(selector): alignment of the selector api

zenoh-jni/src/key_expr.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIKeyExpr.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/KeyExpr.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/SetIntersectionLevel.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/QueryableTest.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/UserAttachmentTest.kt
Adding key expr functions:
- `join(string): Result<KeyExpr>`
- `concat(string): Result<KeyExpr>`
- `relationTo(keyExpr): SetIntersectionLevel`
Removing `keyexpr.undeclare(session)`, leaving only `keyexpr.undeclare()`.
=> KeyExpr alignment

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt
Fix bad behavior introduced in PR #217 where if `tryInitLogFromEnv` is called and the env is not defined, then it's provided an empty string. That doesn't make the logs fail, but it's a wrong logic.
=> Improve tryInitLogFromEnv logic

zenoh-jni/src/config.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Config.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIConfig.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ConfigTest.kt
Adding the following functionalities to Config.kt:
- `config.getJson(key: String): Result<String>`
- `config.insertJson5(key: String, value: String): Result<Unit>`
- `config.id(): ZenohID`
- `Config.fromEnv(): Result<Config>` (attempts to load the config on the path provided under the environment variable `ZENOH_CONFIG`)
=> Config alignment

zenoh-jni/Cargo.lock, zenoh-jni/src/utils.rs
Move zenoh::pubsub::Reliability to zenoh::qos::Reliability. To be merged after https://github.com/eclipse-zenoh/zenoh/pull/1457.
=> Align Rust with Reliability exported in zenoh::qos

examples/build.gradle.kts, examples/src/main/kotlin/io.zenoh/ZInfo.kt, zenoh-jni/src/session.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/SessionInfo.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SessionInfoTest.kt
Adding `SessionInfo` class with the following functions:
- `fun id(): Result<ZenohID>`
- `fun peers(): Result<List<ZenohID>>`
- `fun routers(): Result<List<ZenohID>>`
A Result.failure is returned in case of either:
- JNI error (failure to create a kotlin instance for instance)
- The session has been closed
Also, added the ZInfo example.
=> Session info

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/keyexpr/SetIntersectionLevel.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/PublisherTest.kt
- Adding default encoding argument when declaring a publisher
- Replacing `congestionControl` and `priority` attributes with equivalent functions.
=> Publisher alignment

.github/workflows/publish-jvm.yml, zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Target.kt, zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
ARM64 may not be properly handled when dynamically loading the native libs (see https://github.com/eclipse-zenoh/zenoh-java/issues/155). This PR aims to solve this issue.
On top of that, we add arm64 support for windows.
=> Refactoring JVM target determination + adding arm64 support for windows

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, zenoh-kotlin/build.gradle.kts
- Editing the `build.gradle.kts` file in order to include a publication task for Maven central
- Added package signature (which is required for remote publications)
- Edited the CI workflows for both android and jvm publications.
=> Maven publication: adding Maven central repository

.github/workflows/release.yml, ci/scripts/bump-and-tag.bash
Aligning with [ci repository](https://github.com/eclipse-zenoh/ci/pull/239) to not tag the repo when we are running release dry-run
=> fix: Don't tag release branch during dry-run

.github/workflows/release.yml
Suggestion from eclipse-foundation engineers related to error reading the secret required for maven publication.
=> fix: inherit secrets to pass to reusable workflow

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, zenoh-kotlin/build.gradle.kts
Based on feedback from eclipse-foundation (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5255), maven requires the subkey id to be in short format instead of the full key id.
=> fix: use gpg subkey id to sign maven artifacts

zenoh-jni/src/logger.rs
On some cases (not always) when enabling logging on Android devices, the applications crash due to logging to persistent storage (pstore). This is caused becuase by default, the underlying native library used for android logging sets pstore to true by default.
This PR introduces changes in which if the target is an Android target, it sets the pstore logging to false.
For the record, a discussion regarding this issue took place here: https://discord.com/channels/914168414178779197/1287754571073978449.
=> Android logging: pstore logs disabled

zenoh-jni/src/scouting.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Zenoh.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIScout.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/ScoutTest.kt
This PR fixes the following error: when a scout is launched using a `Channel`, the channel is not closed upon closing the scout.
=> Scouting: closing channel when scout is closed.

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, .github/workflows/release.yml
gradle docs recommends not using --debug in CI since it can potentially leak secrets.
=> fix: remove debug from gradle

examples/build.gradle.kts, examples/src/main/kotlin/io.zenoh/ZQuerier.kt, zenoh-jni/src/lib.rs, zenoh-jni/src/querier.rs, zenoh-jni/src/session.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/annotations/Annotations.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuerier.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Querier.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/QuerierTest.kt
This PR provides the querier functionality on https://github.com/eclipse-zenoh/zenoh/pull/1591.
It also features a querier example, has been tested manually as well as through unit tests.
However this PR does not introduce the following functions available on the Rust API:
- `querier.matching_status()`
- `querier.matching_listener()`
- `querier.accepts_replies()`
- `querier.id()`
=> Adding Querier (unstable) to Zenoh-Kotlin

.github/workflows/ci.yml, .markdownlint.yaml, README.md, examples/README.md
As https://github.com/eclipse-zenoh/zenoh/issues/1666, fix the README.md format and update CI.
=> Add CI for checking markdown format.

zenoh-kotlin/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
**Issue**: when exporting a JAR of a springboot project using Zenoh-Kotlin as a dependency, the native library failed to be loaded. 
**Fix**: fallback to javaClass classloader for loading native lib in case of system class loader failure.
**Tested**: tested manually on a springboot project and on a non springboot project.
Related to https://github.com/eclipse-zenoh/zenoh-java/pull/153
=> Springboot native lib loading: fallback to javaClass classloader

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, build.gradle.kts, zenoh-kotlin/build.gradle.kts
- Adding the [Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) to gradle for the publishing processes
- Modifying the workflows to use the nexus publish tasks
- Modifying the workflows also to allow to manually trigger either the github publication or the maven publication or both by enabling or disabling them from the actions panel:
=> Nexus publish

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonTest/kotlin/io/zenoh/SelectorTest.kt
When sending query to "a/b/c" selector (for instance), the queryable was receiving "a/b/c?null" as selector. 
Bug caused by missing '?' null check.
Manually + added unit test
=> Fix selector "null" parameter

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Querier.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Query.kt
Allowing users to directly pass strings instead of having to convert them into ZBytes using ZBytes.from(string) each time.
This affects:
- session.get/put/delete
- publisher.put/delete
- query.reply/replyErr/replyDel
- querier.get
=> Providing function overloads that receive String params instead of ZBytes

examples/src/main/kotlin/io.zenoh/ZDelete.kt, examples/src/main/kotlin/io.zenoh/ZGet.kt, examples/src/main/kotlin/io.zenoh/ZGetLiveliness.kt, examples/src/main/kotlin/io.zenoh/ZInfo.kt, examples/src/main/kotlin/io.zenoh/ZLiveliness.kt, examples/src/main/kotlin/io.zenoh/ZPong.kt, examples/src/main/kotlin/io.zenoh/ZPub.kt, examples/src/main/kotlin/io.zenoh/ZPubThr.kt, examples/src/main/kotlin/io.zenoh/ZPut.kt, examples/src/main/kotlin/io.zenoh/ZQuerier.kt, examples/src/main/kotlin/io.zenoh/ZQueryable.kt, examples/src/main/kotlin/io.zenoh/ZScout.kt, examples/src/main/kotlin/io.zenoh/ZSub.kt, examples/src/main/kotlin/io.zenoh/ZSubLiveliness.kt
In this PR we attempt to display more didactic examples by
- reducing the nesting by using `getOrThrow()` instead of `onSuccess()` and `onFailure()`
- showing alternative implementations for multiple examples, showing how to use Channels, Handlers and Callbacks.
=> Examples refactor

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml
Otherwise in case of failure of the previous step, this one gets skipped.
=> fix: always upload problem report

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml
Splitting "Gradle Publish JVM Package to Maven Central repository" with "Close & Release Staging Repository". Same for Android publications.
=> Maven publication: splitting publication step on workflows

.github/workflows/release.yml
Only publish the github release and dokka documentation after maven publication succeeds. Otherwise if it fails, makes it harder to cleanup the failed release.
=> fix: publish to github and dokka after maven

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml
Due to https://github.com/gradle-nexus/publish-plugin/issues/96 the call to release staging repository needs to be made together with the publication task.
=> fix: release staging repository with publication

build.gradle.kts, examples/README.md, examples/build.gradle.kts
Adding tasks for creating executable jar's for the examples. The gradle task `buildExamples` will output fat jar's for each of the examples, which can be later run with
```
java -jar <Example>.jar
```
Also the README is updated.
=> Examples fat JARs

.github/workflows/publish-jvm.yml, zenoh-kotlin/build.gradle.kts
Non snapshot packages published to maven central require among other things to contain a javadoc JAR internally.
=> Maven publication: adding javadoc jar to maven publication

.github/workflows/publish-dokka.yml, .github/workflows/publish-jvm.yml, .gitignore, build.gradle.kts, gradle.properties, zenoh-kotlin/build.gradle.kts
This fixes the workflow errors when attempting to build the documentation without enabling android.
=> Upgrade Dokka to 2.0.0

zenoh-kotlin/src/commonMain/kotlin/io/zenoh/Session.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt
Issue: when dropping a Publisher it will remain alive (consuming resources) until the session is closed because of the internal reference in the Session.
The interest of having an internal list of the session declarations inside a session is to clean them up when closing the session.
Fix: for queriers and publishers we store them as weak references which won't prevent their garbage collection.
=> Fix bug: dropping publishers when losing references to them

build.gradle.kts
As per https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6270#note_4175210
we should use central.sonatype.org instead of oss.s.o
=> ci: update sonatype.org url to use new domain

build.gradle.kts
gradle-nexus/publish-plugin uses this new URL to transition to central. See https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuration
=> chore: update maven central url config

zenoh-jni/Cargo.lock, zenoh-jni/src/session.rs, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/config/ZenohId.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNILiveliness.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNIQuerier.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNIGetCallback.kt, zenoh-kotlin/src/commonMain/kotlin/io/zenoh/query/Reply.kt
Depends on https://github.com/eclipse-zenoh/zenoh/pull/2052
This is a breaking change.
=> [ZEN-587] Change `replier_id` type to `EntityGlobalId`
